@Article{Lewis2021,
  author                 = {Lewis, Gail and Thame, Minerva and Howitt, Christina and Hambleton, Ian and Serjeant, Graham},
  journal                = {BJOG : an international journal of obstetrics and gynaecology},
  title                  = {Pregnancy Outcome In Homozygous Sickle Cell Disease: Observations From The Jamaican Birth Cohort.},
  year                   = {2021},
  month                  = {Mar},
  electronic-issn        = {1471-0528},
  linking-issn           = {1470-0328},
  abstract               = {OBJECTIVE: To document pregnancy outcome in homozygous sickle cell (SS) disease and in age-matched controls with a normal haemoglobin genotype followed from birth for up to 45 years. METHODS: A total of 100,000 consecutive non-operative deliveries screened for sickle cell disease at the main Government maternity hospital in Kingston, Jamaica between 1973-1981 detected 311 (149 female) babies with SS disease who were matched by age and gender with 250 (129 female) controls with an AA haemoglobin phenotype. These subjects have been followed from birth with prospective assessment of menarche and detailed documentation of all pregnancies. RESULTS: There were 177 pregnancies in 71 SS patients and 226 pregnancies in 74 AA controls. Mothers with SS disease had more spontaneous abortions [adjusted RR 3.2 (95% CI 1.6, 6.1)], less live births [0.7 (0.6, 0.9)], and their offspring were more likely to have a gestational age < 37 weeks [2.1 (1.1, 3.7)] and low birth weight < 2.5 kg [3.0 (1.6, 5.3)]. They were more prone to acute chest syndrome [13.7 (4.1, 45.5)], urinary tract infection [12.8 (1.3, 125.9)], pre-eclampsia/eclampsia [3.1 (1.1, 8.8)], retained placenta [10.1 (1.1, 90.3)], sepsis (Fisher's Exact test 0.04), and pregnancy-related deaths (Fisher's Exact test 0.02). Four of five deaths were attributable to the acute chest syndrome. There was no genotype difference in pregnancy-induced hypertension or postpartum haemorrhage. CONCLUSION: Pregnancy in SS disease carries risks for both mother and child. The variable characteristics of pregnancy-related deaths complicates their prevention. (240 words).},
  address                = {England},
  article-doi            = {10.1111/1471-0528.16696},
  electronic-publication = {20210308},
  history                = {2021/03/09 06:00 [medline]},
  keywords               = {homozygous sickle cell disease, maternal mortality, pregnancy complications},
  language               = {eng},
  location-id            = {10.1111/1471-0528.16696 [doi]},
  nlm-unique-id          = {100935741},
  owner                  = {NLM},
  publication-status     = {aheadofprint},
  revised                = {20210308},
  source                 = {BJOG. 2021 Mar 8. doi: 10.1111/1471-0528.16696.},
  status                 = {Publisher},
  subset                 = {IM},
  termowner              = {NOTNLM},
  title-abbreviation     = {BJOG},
}
